# path files
path_files:
#   OI file (list of 3 files: nadir, swot, nadir+swot)
    fileOI: "/training/ssh_alg_h2g_j2g_j2n_j3_s3a_duacs.nc"
#   Obs file (list of 3 files: nadir, swot, nadir+swot)
    fileObs: "/training/dataset_nadir__LAG_d.nc"

# data options
data_options:
    lag: _LAG_
    domain: _DOMAIN_
#   load OI: work on SSH or anomaly w.r.t OI (SSH-OI)
    flagloadOIData: 1 
#   use additional covariates in initial layer
    include_covariates: True  
    lfile_cov:
    - "/training/ssh_alg_h2g_j2g_j2n_j3_s3a_duacs.nc"
    lname_cov:
    - ssh
    lid_cov:
    - OI
#   Length of the 4th dimension 
    size_tw: 11
#   half-width of holes
    Wsquare: 4 
#   number of holes
    Nsquare: 3  
    sigNoise: 1e-1
    flagTrOuputWOMissingData: 1
    stdMask: 0.
    dropout: 0.0
    wl2: 0.0000

# NN model options
NN_options:
#   Dimension of the latent space
    DimAE: 40    
#   model type, 1: ConvAE or 2: GENN 3: PINN
    flagAEType: 2     
#   multiscale model
    flag_MultiScaleAEModel: 0 
# load model from NATL60 or not
    load_model: _LMOD_
# add regularization in loss function or not 
    with_regul: _WREGUL_


# loss function weighting
loss_weighting: 
    alpha: !1darray
      - - 1.
        - 0.1
    alpha4DVar: !1darray
      - - 0.
        - 1.
    regul: !1darray
      - - 1.
        - 0.001

# solver parameters
solver_options: 
#   Gradient computation 
#   0: subgradient
#   1: true gradient/autograd
    flagGradModel: 1  
#   Optimization method 
#   0: fixed-step gradient descent
#   1: ConvNet_step gradient descent
#   2: LSTM-based descent
    flagOptimMethod: 1     

# training parameters
training_params:
#   load pre-defined AE model or not   
    flagLoadModel: 0
# batch size for a single GPU  
    batch_size: 4
    NbEpoc: 20
    Niter: 20

