# path files
path_files:
    domain: _DOMAIN_
#   Model file
    fileMod: /ref/NATL60-CJM165__DOMAIN__ssh_y2013.1y.nc
#   OI file (list of 3 files: nadir, swot, nadir+swot)
    fileOI:
    - /oi/ssh_NATL60_4nadir.nc
    - /oi/ssh_NATL60_swot.nc
    - /oi/ssh_NATL60_swot_4nadir.nc
#   Obs file (list of 3 files: nadir, swot, nadir+swot)
    fileObs:
    - /data/gridded_data_swot_wocorr/dataset_nadir__LAG_d.nc
    - /data/gridded_data_swot_wocorr/dataset_swot.nc
    - /data/gridded_data_swot_wocorr/dataset_nadir__LAG_d_swot.nc

# data options
data_options:
    domain: _DOMAIN_
    opt: _OPT_
    lag: _LAG_
    type_obs: _TYPE_OBS_
    flagTrWMissingData: _WMIS_
#   load OI: work on SSH or anomaly w.r.t OI (SSH-OI)
    flagloadOIData: 1
#   use additional covariates in initial layer
    include_covariates: _WCOV_
    lfile_cov:
    - /oi/ssh_NATL60_4nadir.nc
    lname_cov:
    - ssh_mod
    lid_cov:
    - OI
#   Length of the 4th dimension 
    size_tw: 11
#   Dowscaling parameter
    dwscale: 1
#   Index evaluation dates
    start_eval_index: 52
    end_eval_index: 94
#   Index trainig dates
    start_train_index: 122
    end_train_index: 365

# NN model options
NN_options:
#   Dimension of the latent space
    DimAE: 40
#   model type, 1: ConvAE or 2: GENN 3: PINN
    flagAEType: _PHI_

# loss function weighting
loss_weighting:
    alpha: !1darray
      - - 1.
        - 0.1
    alpha4DVar: !1darray
      - - 1.
        - 0.1

# solver parameters
solver_options:
#   FP or Grad
    solver_type: _SOLVER_
#   Gradient computation 
#   0: subgradient
#   1: true gradient/autograd
    flagGradModel: 1
#   Optimization method 
#   0: fixed-step gradient descent
#   1: ConvNet_step gradient descent
#   2: LSTM-based descent
    flagOptimMethod: 1

# training parameters
training_params:
#   load pre-defined AE model or not   
    flagLoadModel: 0
# batch size for a single GPU  
    batch_size: 4
    NbEpoc: 20
    Niter: 20
